### ISSUE TITLE
Is this obsolete yet?

### ISSUE THREAD

**Issue by qm3ster** [sth/babel-plugin-add-filehash#1]
Does the way https://github.com/webpack/webpack/issues/2538 was resolved cover all of the corner cases?

**Comment by sth** [comment]
It fixes the issue of missing error messages, which was the main point of this plugin. It is obsolete for this use case.

Maybe there are other cases where it is still useful. Some loaders may not create error messages but log files or other side effects, and that would not be covered by the Webpack fix. In such a case the add-filehash plugin might still be useful. But I don't have any specific examples in mind.
